// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELtu0Sw3zMoIs3_iKF7P8CevXti1Md8M',
    appId: '1:403771583571:web:58d48a525b1f5be17feaa6',
    messagingSenderId: '403771583571',
    projectId: 'signinproject-d0beb',
    authDomain: 'signinproject-d0beb.firebaseapp.com',
    storageBucket: 'signinproject-d0beb.firebasestorage.app',
    measurementId: 'G-3E8M2P0BX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS1XOQZ6F9j5qpJx8vi3DrAI2J34Qe4zk',
    appId: '1:403771583571:android:d71113e9b43e66ad7feaa6',
    messagingSenderId: '403771583571',
    projectId: 'signinproject-d0beb',
    storageBucket: 'signinproject-d0beb.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBELtu0Sw3zMoIs3_iKF7P8CevXti1Md8M',
    appId: '1:403771583571:web:9e6d6c0a2e9a60d47feaa6',
    messagingSenderId: '403771583571',
    projectId: 'signinproject-d0beb',
    authDomain: 'signinproject-d0beb.firebaseapp.com',
    storageBucket: 'signinproject-d0beb.firebasestorage.app',
    measurementId: 'G-36SVCZ5W55',
  );
}
